from __future__ import annotations

from enum import StrEnum


class WorkflowEventType(StrEnum):
    CONTENT_PRODUCTION_REQUEST_CREATED = "ContentProductionRequestCreated"
    CANDIDATE_SELECTION_REQUESTED = "CandidateSelectionRequested"
    CANDIDATE_SHORTLIST_PREPARED = "CandidateShortlistPrepared"
    CANDIDATE_SHORTLIST_APPROVAL_REQUESTED = "CandidateShortlistApprovalRequested"
    CANDIDATE_SHORTLIST_APPROVED = "CandidateShortlistApproved"
    CANDIDATE_SHORTLIST_REJECTED = "CandidateShortlistRejected"
    CONTENT_SUFFICIENCY_CHECK_REQUESTED = "ContentSufficiencyCheckRequested"
    CONTENT_SUFFICIENCY_CHECKED = "ContentSufficiencyChecked"
    ARTICLE_EXTRACTION_REQUESTED = "ArticleExtractionRequested"
    ARTICLE_EXTRACTED = "ArticleExtracted"
    ARTICLE_EXTRACTION_FAILED = "ArticleExtractionFailed"
    WEB_ENRICHMENT_REQUESTED = "WebEnrichmentRequested"
    WEB_ENRICHED = "WebEnriched"
    WEB_ENRICHMENT_FAILED = "WebEnrichmentFailed"
    EDITORIAL_BRIEF_REQUESTED = "EditorialBriefRequested"
    EDITORIAL_BRIEF_CREATED = "EditorialBriefCreated"
    DRAFT_GENERATION_REQUESTED = "DraftGenerationRequested"
    DRAFT_GENERATED = "DraftGenerated"
    DRAFT_QUALITY_CHECK_REQUESTED = "DraftQualityCheckRequested"
    DRAFT_QUALITY_CHECKED = "DraftQualityChecked"
    DRAFT_REVISION_REQUESTED = "DraftRevisionRequested"
    MEDIA_RESOLUTION_REQUESTED = "MediaResolutionRequested"
    MEDIA_SELECTED = "MediaSelected"
    IMAGE_GENERATION_REQUESTED = "ImageGenerationRequested"
    IMAGE_GENERATED = "ImageGenerated"
    IMAGE_GENERATION_FAILED = "ImageGenerationFailed"
    TELEGRAM_PACKAGE_REQUESTED = "TelegramPackageRequested"
    TELEGRAM_PACKAGE_READY = "TelegramPackageReady"
    FINAL_APPROVAL_REQUESTED = "FinalApprovalRequested"
    POST_PACKAGE_APPROVED = "PostPackageApproved"
    POST_PACKAGE_REJECTED = "PostPackageRejected"
    TELEGRAM_DISPATCH_REQUESTED = "TelegramDispatchRequested"
    TELEGRAM_POST_PUBLISHED = "TelegramPostPublished"
    TELEGRAM_POST_FAILED = "TelegramPostFailed"
    PRODUCTION_RUN_FAILED = "ProductionRunFailed"
